### ISSUE TITLE
Rays aren't always smooth in appearance

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics#392] opened 2022-03-21 19:35 UTC
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3

**Browser**
Safari and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/787

Some rays don't look smooth. As you move the object, which rays appear rough and which appear smooth changes. This is particularly noticeable when moving the object slowly with keyboard nav. Looking at the published prototype, the rays always appear smooth, with the dark or light background. 

**Steps to reproduce**
On either screen slowly move the framed object in any direction with the mouse or with keyboard nav. 

**Visuals**
<img width="415" alt="Screen Shot 2022-03-21 at 3 16 34 PM" src="https://user-images.githubusercontent.com/87318828/159349135-c815f4b4-f4e1-4074-a205-71e87182753e.png">

<img width="675" alt="Screen Shot 2022-03-21 at 3 20 42 PM" src="https://user-images.githubusercontent.com/87318828/159350345-3a95af66-490f-4a36-9129-7ff1c0f7e94c.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!

Name: ‪Geometric Optics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-rc.1/phet/geometric-optics_all_phet.html
Version: 1.1.0-rc.1 2022-03-18 20:41:59 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36
Language: en-US
Window: 1369x678
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment] 2022-03-21 19:50
After pressing the zoom out button once: 
<img width="653" alt="Screen Shot 2022-03-21 at 3 47 09 PM" src="https://user-images.githubusercontent.com/87318828/159352634-6ec99ffe-3de0-4e19-ab57-fdbe4eee82a3.png">

**Comment by pixelzoom** [comment] 2022-03-21 20:41
Rays are drawn as a set of scenery Line segments.  What you're seeing is aliasing, which is more noticable with lines that are not horiontal or vertical.  And it honestly doesn't look too bad too me.

I haven't made changes to the ray tracer since publishing the prototype.  So I think the aliasing is more noticeable because we inverted the color profile.  We now have dark lines on a white background.  To confirm that aliasing is more noticeable on a white background, run the sim in the Color Editor, and change colors `screenBackgroundColor` and `realRayOneStroke`.  

If I zoom out in the prototype, I see the same aliasing that's reported above. Here are screenshots from the prototype for the 2 zoomed-out views.

<img width="727" alt="screenshot_1621" src="https://user-images.githubusercontent.com/3046552/159358729-05356ca4-ce62-4924-8211-92a10b703691.png">
<img width="774" alt="screenshot_1620" src="https://user-images.githubusercontent.com/3046552/159358711-b447ca87-a13d-41ea-9232-1666d92cd522.png">

I also confirmed in the code that we're using a reasonable number of Line instances for each set of rays.  For Marginal and Principal rays, it's typically 9 Lines for real rays, 3 Lines for virtual rays.  For Many rays it's of course more, but certainly < 40 Lines when fully zoomed-in.

I'll check with @jonathanolson to see if there's any additional scenery magic that can be applied here.

**Comment by pixelzoom** [comment] 2022-03-21 20:41
@arouinfar could you also weigh in on whether this is an issue that needs to be addressed?

**Comment by pixelzoom** [comment] 2022-03-21 22:28
@jonathanolson and I discussed on Zoom.  We tried `rootRenderer=canvas`, but it actually looks worse with Canvas.  If it's really not acceptable, @jonathanolson will dive in to see if there's anything else to be done.  

@arouinfar your call.

**Comment by arouinfar** [comment] 2022-03-22 22:26
Thanks for reporting @Nancy-Salpepi.

It's possible that reducing the stroke weight of the rays to 1.5 may be contributing to some of the aliasing. However, I think it's minor enough to ignore, so closing.

**Closed by arouinfar** 2022-03-22 22:26 UTC
Labels: type:performance

**Comment by pixelzoom** [comment] 2022-03-22 22:34
> It's possible that reducing the stroke weight of the rays to 1.5 may be contributing to some of the aliasing.

I tried bumping it back up to `lineWidth:2` and there's no noticeable change.
