### ISSUE TITLE
Rays from object disappear behind object in concave mirror scene

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#394] opened 2022-03-21 20:36 UTC
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/787
If the object is behind the image created by the concave mirror, the rays that should come from the top of the picture (or second point) will be layered under the object.
**Steps to reproduce**
1. Go to the mirror screen
2. On the concave scene, drag the object to the left side of the screen

**Visuals**
<img width="959" alt="raybehindobject" src="https://user-images.githubusercontent.com/41024075/159359452-2ba31f99-09f0-4861-894b-0d76e074150b.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-rc.1/phet/geometric-optics_all_phet.html
Version: 1.1.0-rc.1 2022-03-18 20:41:59 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0
Language: en-US
Window: 1280x667
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Nancy-Salpepi** [comment] 2022-03-21 20:46
Also happens with the second point on the framed object. I don't see it occur with the arrows
<img width="541" alt="Screen Shot 2022-03-21 at 4 45 00 PM" src="https://user-images.githubusercontent.com/87318828/159360739-79c5d095-3ef0-4ebf-aa6f-24f957e7aaa7.png">

**Comment by pixelzoom** [comment] 2022-03-21 20:55
Reproduced in 1.1.0-rc.1 and master.   This problem was introduced between 1.1.0-dev.24 (2/11/22 20:44) and 1.1.0-dev.25 (2/14/22 16:38). 

This problem is unique to framed objects, because they are the only type of object that has 3D perspective.  In the case shown above, the rays that are front of the framed object are being incorrectly clipped.   I'll need to adjust the `clipArea` in RealLightRaysForegroundNode.

**Comment by pixelzoom** [comment] 2022-03-21 21:12
This is actually a rendering order problem, not a clipArea problem. In https://github.com/phetsims/geometric-optics/commit/7eff8807e11130602b2979e2d9f1775bbfa8eb5c, GOSceneNode was factored out, and that changes rendering order, as I had to tease out the Nodes that are common to all scenes.  


Running with `?debugRays` in 1.1.0-dev.24, we can see that `realLightRays1Node` (the gray ray segements) is in front of `framedObjectNode`:

<img width="657" alt="screenshot_1624" src="https://user-images.githubusercontent.com/3046552/159364469-5283416a-0ae1-4b45-a395-ca85a7c5baf5.png">

In 1.1.0-dev.25, `realLightRays1Node` is now _behind_ `framedObjectNode`:

<img width="676" alt="screenshot_1625" src="https://user-images.githubusercontent.com/3046552/159364527-fdeba4e2-9b8b-4f18-8d31-309a5077f557.png">

**Comment by pixelzoom** [comment] 2022-03-21 21:39
Fixed in master and 1.1 branches, see screenshot below.

The `debugRays` query parameter also was broken (probably when I converted to the new TypeScritpt options pattern) and that's also fixed.

@Nancy-Salpepi please verify in master. If it looks OK, change the issue label to "status:fixed-awaiting-deloy".  Thanks!

<img width="1202" alt="screenshot_1627" src="https://user-images.githubusercontent.com/3046552/159368073-6ed84e0f-bf97-49a7-845e-ef8e77a4ed55.png">

**Comment by pixelzoom** [comment] 2022-03-21 21:40
Sorry, I see that @KatieWoe originally reported this, so I'll assign to her.

**Comment by KatieWoe** [comment] 2022-03-21 21:54
Looks fixed on master

**Comment by pixelzoom** [comment] 2022-03-31 17:02
To verify in 1.1.0-rc.2, follow "steps to reproduce" in https://github.com/phetsims/geometric-optics/issues/394#issue-1175913862.

If it looks OK, close this issue.

**Comment by Nancy-Salpepi** [comment] 2022-04-01 16:45
Looks fixed!

**Closed by Nancy-Salpepi** 2022-04-01 16:45 UTC
Labels: type:bug, status:ready-for-review
