### ISSUE TITLE
Virtual rays converge on empty space

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics#260] opened 2021-10-26 15:55 UTC
**Test device**
iMac

**Operating System**
11.15.7

**Browser**
safari 
(but also seen on MacBook Air iOS 12 + chrome)

**Problem description**
https://github.com/phetsims/qa/issues/727

With 'Many' rays selected, when Object is close to Optic but above optic axis, the virtual rays from the Second Point seem to converge on nothing. This occurs when none of the Real Rays from the Object pass through the Optic. 

**Steps to reproduce**
1. Select either screen
2. Select 'Many' for Rays
3. Select 'Second Point'
4. Move Object to the Optic and upward

**Visuals**

![virtualrays](https://user-images.githubusercontent.com/87318828/138915019-13220757-164f-4b35-8198-1c4fbe8ae638.gif)
![Screen Shot 2021-10-26 at 11 51 44 AM](https://user-images.githubusercontent.com/87318828/138915443-2382a005-6275-4006-a70b-e38c55ad3e95.png)

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics/1.0.0-rc.1/phet/geometric-optics_all_phet.html
Version: 1.0.0-rc.1 2021-10-18 23:43:38 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15
Language: en
Window: 1409x778
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment] 2022-01-18 21:12
This was a problem when the Object got close to the optic, and the last version that exhibits the problem is 1.1.0-dev.3. This became a non-problem in 1.1.0-dev.4 (11/10/21) when increased the minimum distance between the Object and optic.  

Closing.

**Closed by pixelzoom** 2022-01-18 21:12 UTC
Labels: type:bug, priority:5-deferred
