### ISSUE TITLE
Ray Animation and other component interactions

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#59] opened 2021-06-24 19:02 UTC
This is the master issue for all the ray tracing.
We should come up with a list of requirements with corresponding issues.

**Comment by veillette** [comment] 2021-06-24 19:29
When on 'show', rays should emerge from the object, pass through the optic, and once they converge, the image appears. In the case when rays diverge, virtual rays should also be animated and the virtual image should appear.

'Hide' should make rays and image disappear.

**Comment by veillette** [comment] 2021-06-24 20:03
if the optic produces a real image, this image should appear only after the rays reached the image position.

if the optic produces a virtual image, this image should appear only after the rays reached the image position and the virtual check box is turned on.

If the checkbox labels is on, the label for the image should only appear after the rays reached the image.

**Comment by veillette** [comment] 2021-06-25 14:48
if any of the properties that affect the rays, (such at the position of the optic, source,  representation, diameter, focal length, radius of curvature), the rays animation is stopped, and restart at zero.

**Comment by veillette** [comment] 2021-06-25 15:10
We can create two properties called  say: rayTerminated, and movableRayTerminated. We can wire them to the projector spots, the image label , and the image.

The real image would appear if ray terminated is on and would be invisible otherwise.

The virtual image would appear is the checkbox is set to isVirtual, the image is virtual and if the ray is terminated. ALl these conditions must be fulfilled in order for the virtual image to be visible.

The label image would appear if ray terminated is on, and the label checkbox is on. Otherwise the label is invisible.

The projector spot linked to the position of the first source, would appear once the ray is terminated.

the projector spot linked to the movable point would appear once, the movableRayTerminated is on.

**Comment by sarchang** [comment] 2021-07-01 22:37
### Expected behaviors
**With `Hide` toggled:**
- `Rays` ON/OFF: Rays do not appear
     - `Virtual Image` 
          - ON/OFF: no image will appear (not even a real one)
     - `Labels` 
          - ON: labels should appear for visible components
          - OFF: no change
     - `Movable Point`
          - ON: dot should appear on object, no rays
          - OFF: no change

**With `Show` toggled:**
- `Rays` ON: Rays animate
     - `Virtual Image` 
          - ON: virtual image and virtual rays will appear with animation; if animation is complete, virtual image/rays will appear instantaneously
          - OFF: virtual image and virtual rays will not appear with animation (but real image and real rays will still animate)
     - `Labels` 
          - ON: labels should appear for visible components; image label should appear when image is displayed (after animation)          
          - OFF: no change
     - `Movable Point`
          - ON: dot should appear on object, rays appear instantaneously (no animation); virtual image/rays should toggle with `Virtual Image` checkbox
          - OFF: no change
- `Rays` OFF: Rays do not appear
     - `Virtual Image` 
          - ON: real/virtual image appears instantaneously
          - OFF: no change
     - `Labels` 
          - ON: labels should appear for visible components (appears instantaneously with real/virtual image)
          - OFF: no change
     - `Movable Point`
          - ON: dot should appear instantaneously on object
          - OFF: no change

**Comment by sarchang** [comment] 2021-07-02 18:43
Tested all the different expected behaviors; everything is working as expected with the objects (pencil, tree, rocket) and with both lens and mirror. Ran into many clicking/multiple selection issues with Macbook Air M1. Now focusing on fixing the spotlight/screen option.

**Comment by sarchang** [comment] 2021-07-02 19:36
Only tasks left are on the light/projector screen:

If the source of light is present, the projector screen should always be present and the **rays should terminate** on the projector screen. The spotlight should show up when the rays reach it the projector screen. (tracking in #13)

If the movable point is checked on and the representation is set to light, the rays should be animated and the spotlight will appear once the rays hit the projector screen. The time of arrival of the rays may not match the time of arrival of the other source of light since they may be at a different distance.

**Comment by sarchang** [comment] 2021-07-02 20:37
Closing and tracking leftover tasks in #13 and #69.

**Closed by sarchang** 2021-07-02 20:37 UTC
Labels: Ray Animation
