### ISSUE TITLE
Tool disappears if sim is launched while zoomed out

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#468] opened 2023-05-12 16:23 UTC
**Device**
Samsung
**OS**
Win 11
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/qa/issues/938 and https://github.com/phetsims/qa/issues/939. May be related to https://github.com/phetsims/geometric-optics/issues/467.
If you launch the sim with a tool like a ruler in the scene, and you are zoomed out with the zoom buttons, the tool may be in a different place or gone entirely in the launched sim.
**Steps**
1. Remove a ruler from the tool box
2. Zoom out all the way with the scene zoom buttons
3. Launch the sim

**Visuals**
![Geometric Optics screenshot](https://github.com/phetsims/geometric-optics/assets/41024075/613517c4-67ed-4037-9245-21946f152e4a)

**Comment by pixelzoom** [comment] 2023-05-15 00:24
This is a duplicate of #467.  If the tool is removed from the toolbox and placed near the top of the screen, then it will be off the top of the screen in the Standard Wrapper (Test). 

For example, if you place a ruler like this in Studio:

<img width="637" alt="screenshot_2514" src="https://github.com/phetsims/geometric-optics/assets/3046552/5a697514-a40d-4034-b1b6-d67e34374876">

Then press the "Test" button and you'll see what @KatieWoe reported above.  But if you resize the browser window, then you'll see the ruler way up above the toolbox:

<img width="397" alt="screenshot_2513" src="https://github.com/phetsims/geometric-optics/assets/3046552/26f4e093-2008-4cd4-83be-c460d6c8550e">

**Closed by pixelzoom** 2023-05-15 00:24 UTC
Labels: type:bug
