### ISSUE TITLE
Can projector mode be deleted?

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/geometric-optics#332] opened 2022-02-26 02:16 UTC
@pixelzoom @arouinfar do we need projector mode anymore in the options? It seems that is now unnecessary with the background color choices and such?

Found as part of #328

**Comment by pixelzoom** [comment] 2022-02-26 02:20
This is a duplicate of an issue that was hanging around a long time https://github.com/phetsims/geometric-optics/issues/275. We recently decided to roll all issues related to color into https://github.com/phetsims/geometric-optics/issues/319.   So I'm going to close this as a duplicate of https://github.com/phetsims/geometric-optics/issues/319.

**Closed by pixelzoom** 2022-02-26 02:20 UTC
Labels: design:polish
