### ISSUE TITLE
Image appears with Hide Button selected

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics#257] opened 2021-10-22 13:10 UTC
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.6

**Browser**
chrome

**Problem description**
https://github.com/phetsims/qa/issues/727

In both the Lens and Mirror Screens, with the Hide Button selected, the image appears with the  'None' Ray Option.

**Steps to reproduce**
1. Select either Screen 
2. Press Hide Button
3. Choose 'None' for Ray Option
4. Move the Object--its image will appear

**Visuals**

![imageappears](https://user-images.githubusercontent.com/87318828/138458592-3e1971ce-450b-41dd-9af1-1783a3dfdf4f.gif)

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics/1.0.0-rc.1/phet/geometric-optics_all_phet.html
Version: 1.0.0-rc.1 2021-10-18 23:43:38 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
Language: en-US
Window: 1431x690
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment] 2022-01-28 23:59
I can no longer reproduce this -- it seems to have fixed itself after the numerous changes that have been made.  @arouinfar please confirm, and close if you agree.

**Comment by arouinfar** [comment] 2022-02-09 18:28
@pixelzoom I've also been unable to reproduce in master, closing.

**Closed by arouinfar** 2022-02-09 18:28 UTC
Labels: type:bug, status:ready-for-review
