### ISSUE TITLE
Light stops propagating early at extreme dimensions

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#480] opened 2023-06-01 16:53 UTC
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/947 and https://github.com/phetsims/qa/issues/948.
If the window is very short, wide, and zoomed out, the light will stop propagating before the edge of the screen, potentially before the lens/mirror. This take some absurd dimensions.
**Steps to reproduce**
1. Make the window short and wide
2. Zoom out as far as possible
3. Move the object to the far left of the screen

**Visuals**
![sillystop](https://github.com/phetsims/geometric-optics/assets/41024075/5fbd8f35-186d-4a9d-b74e-ab66140d4af5)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics: Basics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics-basics/1.3.0-rc.2/phet/geometric-optics-basics_all_phet.html
Version: 1.3.0-rc.2 2023-05-22 20:06:40 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Language: en-US
Window: 1536x731
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment] 2023-06-01 17:07
Nice! Reproduced in master on macOS + Firefox.   Cannot reproduce on macOS + Chrome  or Safari, because those browsers will not let me make the browser window that small.

This definitely does not block publication. But I'm curious about the case, so I'll investigate a bit.

**Comment by pixelzoom** [comment] 2023-06-01 17:12
I also see that before rays fail to reach the optic, they fail to propagate fully to the _right_ of the optic. For example, the ray that the red arrow is pointing to in this screenshot:

![screenshot_2556](https://github.com/phetsims/geometric-optics/assets/3046552/50e89ab1-ec16-4d16-ab35-0e12bbd945c7)

**Comment by pixelzoom** [comment] 2023-06-01 17:19
I spent ~15 minutes and did not immediately determine why this is happening.

The screenshot below shows the (approximate) minimum window height where things work correctly. Any height smaller than this is where the problem becomes apparent.   A window of this size is never going to be used in practice, because the sim is generally unusable at this window size.   

So...  This is not a problem in practice, and I'm not going to spend more time on it.  Closing as "won't fix". 

<img width="1263" alt="screenshot_2557" src="https://github.com/phetsims/geometric-optics/assets/3046552/57d3a0f4-efdd-4487-8d0c-e035d6beb094">

**Closed by pixelzoom** 2023-06-01 17:19 UTC
Labels: type:bug
