### ISSUE TITLE
CT Cannot normalize a zero-magnitude vector

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#408] opened 2022-03-28 16:41 UTC
Also in Basics
```
geometric-optics : interactive-description-fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648297138018/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1648297138018%22%2C%22timestamp%22%3A1648301949934%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Query: fuzz&supportsInteractiveDescription=true&memoryLimit=1000
Uncaught Error: Cannot normalize a zero-magnitude vector
Error: Cannot normalize a zero-magnitude vector
at Vi.normalized (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648297138018/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1648297138018%22%2C%22timestamp%22%3A1648301949934%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:882:118840)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648297138018/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1648297138018%22%2C%22timestamp%22%3A1648301949934%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:882:1514246
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648297138018/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1648297138018%22%2C%22timestamp%22%3A1648301949934%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:882:1514446
at r (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648297138018/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1648297138018%22%2C%22timestamp%22%3A1648301949934%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:882:73806)
at At.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648297138018/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1648297138018%22%2C%22timestamp%22%3A1648301949934%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:882:48182)
at Dv._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648297138018/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1648297138018%22%2C%22timestamp%22%3A1648301949934%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:882:81713)
at Dv.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648297138018/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1648297138018%22%2C%22timestamp%22%3A1648301949934%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:882:81090)
at Dv.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648297138018/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1648297138018%22%2C%22timestamp%22%3A1648301949934%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:882:82214)
at Xc.reposition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648297138018/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1648297138018%22%2C%22timestamp%22%3A1648301949934%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:882:686634)
at Xc._dragAction.fl.parameters.name (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648297138018/geometric-optics/build/phet/geometric-optics_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22interactive-description-fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1648297138018%22%2C%22timestamp%22%3A1648301949934%7D&fuzz&supportsInteractiveDescription=true&memoryLimit=1000:882:683600)
id: Bayes Chrome
Snapshot from 3/26/2022, 6:18:58 AM
```

**Comment by pixelzoom** [comment] 2022-03-28 16:45
Duplicate of https://github.com/phetsims/geometric-optics/issues/178.

**Closed by pixelzoom** 2022-03-28 16:45 UTC
Labels: type:automated-testing
