### ISSUE TITLE
The dragHandler for the second source has an offset.

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#82] opened 2021-07-07 18:24 UTC

**Comment by veillette** [comment] 2021-07-07 18:51
As part of the work on #79, we noticed that there is an offset to the second source on start event off the dragListener. This is present solely on the movable source of light and  not on the movable object.

**Comment by pixelzoom** [comment] 2021-09-15 23:40
Duplicate of https://github.com/phetsims/geometric-optics/issues/191.  https://github.com/phetsims/geometric-optics/issues/191 has more details and steps to reproduce, so closing this issue.

**Closed by pixelzoom** 2021-09-15 23:40 UTC
Labels: type:bug
