### ISSUE TITLE
Chrome DevTools reports 2 issues in the "Issues" tab.

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics#476] opened 2023-05-31 14:10 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
13.4

**Browser**
Chrome 113.0.5672.126

**Problem description**
For https://github.com/phetsims/qa/issues/947 and https://github.com/phetsims/qa/issues/948, I see this issue in the console for the State Wrapper:
<img width="303" alt="Screenshot 2023-05-31 at 10 06 39 AM" src="https://github.com/phetsims/geometric-optics/assets/87318828/0588867f-1963-4c96-b0ad-dab614fced45">

**Comment by pixelzoom** [comment] 2023-05-31 14:29
I cannot reproduce in 1.3.0-rc.2 or master for either sim.  I'm on macOS 13.3.1 (a) and Chrome 114.0.5735.9.

I'll try updating to macOS 13.4.

@Nancy-Salpepi what version of Chrome are you using? Do you see this problem with Safari or Firefox?

**Comment by pixelzoom** [comment] 2023-05-31 14:58
Thanks @Nancy-Salpepi.  One more request... Can you reproduce these problems in master? That will tell us whether the problem is still present in the PhET code base.

**Comment by Nancy-Salpepi** [comment] 2023-05-31 15:09
Yes--they are on master as well. After the sim loads, you will see them in the Issues tab (same as the RC version). 
<img width="303" alt="Screenshot 2023-05-31 at 11 07 28 AM" src="https://github.com/phetsims/geometric-optics/assets/87318828/2677bb57-b76e-47a6-a923-9609e3f95844">

**Comment by KatieWoe** [comment] 2023-05-31 15:44
I checked the recent Density RC and did not see this there (MacOS 13.4 + Chrome)

**Comment by pixelzoom** [comment] 2023-05-31 20:23
I am unable to reproduce in 1.3.0-rc.2 or master after updating to macOS 13.4.  I'm still using Chrome 114.0.5735.9.

I don't know how to proceed with this issue.

**Comment by pixelzoom** [comment] 2023-05-31 20:49
I got on Zoom with @Nancy-Salpepi to see what I was doing wrong.  I was not clicking on the "Issues" tab, as @Nancy-Salpepi instructed in https://github.com/phetsims/geometric-optics/issues/476#issuecomment-1570420994.

So I can now reproduce this in 1.3.0-rc.2 and master with macOS 13.4 and Chrome 114.0.5735.9.
After stating the State Wrapper, then clicking on the "Issues" tab, here's what I see:

<img width="716" alt="screenshot_2544" src="https://github.com/phetsims/geometric-optics/assets/3046552/342b7a43-4b20-41c9-8044-29069c2196c0">

**Comment by pixelzoom** [comment] 2023-05-31 20:56
I see the "Audit usage..." issue with anything that I lauch from phetmarks.  It doesn't have to be the State Wrapper, it can be a standalone sim.

**Comment by pixelzoom** [comment] 2023-05-31 21:05
[Chrome DevTools documentation](https://developer.chrome.com/docs/devtools/issues/) for the Issues tab says:

<img width="663" alt="screenshot_2548" src="https://github.com/phetsims/geometric-optics/assets/3046552/af411ebe-c0fb-42ba-b992-69a8f3595385">


Mousing over the blue icon for our issues, I see this tooltip., which identifies these are "room for improvement":

<img width="540" alt="screenshot_2547" src="https://github.com/phetsims/geometric-optics/assets/3046552/0ad97a25-032d-4c83-8a3f-70ab841abc9e">

So I recommend that we do nothing and close this issue.  @arouinfar thoughts?

**Comment by pixelzoom** [comment] 2023-05-31 21:12
When running the standalone sim (either brand) the "No label..." issue looks like this:

<img width="698" alt="screenshot_2549" src="https://github.com/phetsims/geometric-optics/assets/3046552/61f0ee3b-8e10-4ccf-a425-340be4f331ca">

Expanding the "13 resources":

<img width="716" alt="screenshot_2550" src="https://github.com/phetsims/geometric-optics/assets/3046552/9856ad33-0929-494e-9a92-f14e83fa3b66">

Selecting the first "Violating node" shows this in the _Elements_ tab:

<img width="530" alt="screenshot_2551" src="https://github.com/phetsims/geometric-optics/assets/3046552/e406f544-9a94-4ca0-9441-abad1097c008">

And in fact ever "Violating node" is `<label data-focusable="false" class="a11y-pdom-element"`. So there's something going on with a11y and the PDOM here. @jessegreenberg any idea what might be happening?

**Comment by pixelzoom** [comment] 2023-05-31 21:26
It turns out that these 2 DevTools Issues are unrelated.  And this GitHub issue is getting confusing. So I'm going to break these this into 2 separate GitHub issues.

**Comment by pixelzoom** [comment] 2023-05-31 21:34
The "No label..." Issue has been moved to https://github.com/phetsims/geometric-optics/issues/478.

**Comment by pixelzoom** [comment] 2023-05-31 21:46
The "Audit usage..." issue has been moved to https://github.com/phetsims/geometric-optics/issues/479.

Closing this issue.

**Closed** 2023-05-31 21:47 UTC
Labels: dev:phet-io
