### ISSUE TITLE
Marker skips over arrow at left edge when using hot key

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics#473] opened 2023-05-26 14:26 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
13.3.1

**Browser**
Safari 16.4

**Problem description**
For https://github.com/phetsims/qa/issues/947, If I place the arrow at the left edge of the screen it will be skipped over by the position marker when pressing `J`.

**Steps to reproduce**
1. On either screen, place the blue arrow on the left side of the screen.
2. Use keyboard nav to grab a position marker from the toolbox.
3. Press `J` repeatedly

**Visuals**

https://github.com/phetsims/geometric-optics/assets/87318828/a682e8e6-00d6-4231-82a0-ca81f57594ca

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics/1.3.0-rc.2/phet/geometric-optics_all_phet.html
Version: 1.3.0-rc.2 2023-05-22 19:56:35 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Language: en-US
Window: 1561x775
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment] 2023-05-26 17:37
The Position Marker will also not jump to the arrow image if it is at the right edge of the screen:
<img width="1216" alt="Screenshot 2023-05-26 at 1 35 25 PM" src="https://github.com/phetsims/geometric-optics/assets/87318828/a3c58d62-d65b-42a4-b01a-7ee3cef8a6d7">

**Comment by pixelzoom** [comment] 2023-05-26 18:07
Reproduced in master.

I thought this might be relates to layoutBounds, but it's not.  I ran with `?dev`, and pressing "J' visits the arrow when it's outside the layoutBounds.  See screenshot below.

If I move the arrow in a few pixels from the edge of the screen's visibleBounds, then pressing "J" does visit the arrow.

My WAG at what's causing the problem: When the arrow is at the extreme edges of the screen, some part of it's bounds are not inside the screen's visibleBounds, and the arrow is then excluded from the things that the positon marker visits.

**Comment by pixelzoom** [comment] 2023-05-26 18:38
Noting that the rulers (GORulerNode) do not suffer from this problem.   So I should start by comparing the implementations of `jumpToPoint` in GORulerNode and PositionMarkerNode.

**Comment by pixelzoom** [comment] 2023-05-26 18:43
Adding a `console.log` in PositionMarkerNode.ts like this:

```ts
    // Find the points that are relevant.
    const relevantJumpPoints = this.jumpPoints.filter( jumpPoint =>

      // not null
      ( jumpPoint.positionProperty.value !== null ) &&

      // visible
      jumpPoint.visibleProperty.value &&

      // inside the tool's drag bounds, so the tool doesn't move out of bounds
      this.dragBoundsProperty.value.containsPoint( jumpPoint.positionProperty.value )
    );
    console.log( `${this.phetioID} relevantJumpPoints.length=${relevantJumpPoints.length}` );
```

... shows that the number `relevantJumpPoints` decreases from 5 to 4 when the arrow is positioned at the left edge of the screen.   And this line in particular is probably where things are going wrong:

```ts
165      this.dragBoundsProperty.value.containsPoint( jumpPoint.positionProperty.value )
```

**Comment by pixelzoom** [comment] 2023-05-26 18:55
Adding more debugging output in  PositionMarkerNode.ts:

```ts
    // Find the points that are relevant.
    const relevantJumpPoints = this.jumpPoints.filter( jumpPoint =>

      // not null
      ( jumpPoint.positionProperty.value !== null ) &&

      // visible
      jumpPoint.visibleProperty.value &&

      // inside the tool's drag bounds, so the tool doesn't move out of bounds
      this.dragBoundsProperty.value.containsPoint( jumpPoint.positionProperty.value )
    );
    console.log( `dragBounds=${this.dragBoundsProperty}` );
    for ( let i = 0; i < this.jumpPoints.length; i++ ) {
      const jumpPoint = this.jumpPoints[ i ];
      if ( jumpPoint.positionProperty.value !== null && jumpPoint.visibleProperty.value ) {
        console.log( `${this.tandem.name} i=${i} jumpPoint=${jumpPoint.positionProperty.value} inBounds=${this.dragBoundsProperty.value.containsPoint( jumpPoint.positionProperty.value )}` );
      }
    }
```

When the arrow is at the left edge of the screen, the console output is (e.g.):

```
dragBounds=Property#1367{[x:(-250.06,250.06),y:(-179.76652449845335,163.1060606060606)]}
positionMarker1Node i=0 jumpPoint=Vector2(0, 0) inBounds=true
positionMarker1Node i=1 jumpPoint=Vector2(-80, 0) inBounds=true
positionMarker1Node i=2 jumpPoint=Vector2(80, 0) inBounds=true
positionMarker1Node i=5 jumpPoint=Vector2(-251.5, 63.88585960410556) inBounds=false
positionMarker1Node i=7 jumpPoint=Vector2(117.31778425655976, -29.800984071885974) inBounds=true
```

So the arrow (at jumpPoint `i=5`) is just outside the dragBounds.  Now I'll need to investigate how that is possible. I'm guessing that the jumpPoint be different than the arrow's position.

**Comment by pixelzoom** [comment] 2023-05-26 19:32
> So I'm guessing that the jumpPoint's position is different than the arrow's position.

Not the case. They are the same positionProperty.

In ArrowSceneNode.ts:

```ts
      new ToolJumpPoint( scene.arrowObject1.positionProperty, arrowObject1Node.visibleProperty ),
      new ToolJumpPoint( scene.arrowObject2.positionProperty, arrowObject2Node.visibleProperty ),
```

In ToolJumpPoint.ts:

```ts
  public constructor( positionProperty: TReadOnlyProperty<Vector2>, visibleProperty: TReadOnlyProperty<boolean> ) {
    this.positionProperty = positionProperty;
    this.visibleProperty = visibleProperty;
  }
```

So it seems that the arrowObject.positionProperty is outside the dragBounds. But the arrow's position is at the tip of the arrow head, which is clearly inside the screen's visibleBounds.  So my next guess is that the dragBounds is an eroded version of the screen's visibleBounds.  And the drag listener for arrow is not using the same dragBounds as the "J" feature.

**Comment by pixelzoom** [comment] 2023-05-30 18:31
The dragBounds in ArrowObjectNode (use to constrain dragging of the arrow) is different than the dragBounds in PositionMarkerNode.ts (used to determine whether the arrow should be considered when using "J" to move the marker).

For example in ArrowObjectNode, we have `dragBoundsProperty.value=[x:(-251.5,-40),y:(-80,80)]`, while in PositonMarkerNode.ts, we have `dragBoundsProperty.value=[x:(-250.06,250.06)`.    So dragging the arrow to the far left results in is positon having `x=-251.5`, which is outside the dragBounds used by the position marker.

**Comment by pixelzoom** [comment] 2023-05-30 18:34
Here's the dragBoundProperty derivation in PositionMarkerNode.ts:

```ts

    // Drag bounds for the marker, in model coordinates.
    // This keeps the entire marker inside the visible bounds of the ScreenView.
    this.dragBoundsProperty = new DerivedProperty(
      [ visibleBoundsProperty, zoomTransformProperty ],
      ( visibleBounds, zoomTransform ) => {
        const viewBounds = new Bounds2( visibleBounds.minX + this.width / 2, visibleBounds.minY,
          visibleBounds.maxX - this.width / 2, visibleBounds.maxY - this.height );
        return zoomTransform.viewToModelBounds( viewBounds );
      }
    );
```

And in ArrowObjectNode.ts:

```ts
    const dragBoundsProperty = new DerivedProperty(
      [ sceneBoundsProperty, objectDragModeProperty ],
      ( sceneBounds, objectDragMode ) => {

        const minX = sceneBounds.minX + modelViewTransform.viewToModelDeltaX( arrowNode.width ) / 2;
        const maxX = optic.positionProperty.value.x - GOConstants.MIN_DISTANCE_FROM_OBJECT_TO_OPTIC;
        let minY: number;
        let maxY: number;

        if ( objectDragMode === 'freeDragging' ) {

          // Constrain to the smaller of sceneBounds or MAX_MAGNITUDE. See https://github.com/phetsims/geometric-optics/issues/429
          minY = Math.max( sceneBounds.minY, optic.positionProperty.value.x - ArrowObject.MAX_MAGNITUDE );
          maxY = Math.min( sceneBounds.maxY, optic.positionProperty.value.x + ArrowObject.MAX_MAGNITUDE );
        }
        else {

          // horizontal dragging, locked to the object's current y position
          minY = arrowObject.positionProperty.value.y;
          maxY = arrowObject.positionProperty.value.y;
        }
        return new Bounds2( minX, minY, maxX, maxY );
      } );
```

**Comment by pixelzoom** [comment] 2023-05-30 18:55
I pushed a fix in the above commit.  But it involves a design change that I should run past @arouinfar.

Dragging of position markers is constrained such that the entire Node must be inside the visibleBounds of the screen.  So when an arrow is at the far left of the screen, we can't actually place a marker at the arrow position. This is as close as we can get:

<img width="62" alt="screenshot_2539" src="https://github.com/phetsims/geometric-optics/assets/3046552/e64fe1b5-44f5-47a9-959b-3bd4d8405795">

And that's also why we can't jump to that position with the "J" key.

To address this, we need to relax the drag constraint on the position markers, so that _half of the Node width_ must be in bounds.  This allows us to drag a position marker, or jump, to the above arrow:

<img width="54" alt="screenshot_2540" src="https://github.com/phetsims/geometric-optics/assets/3046552/cea9a90b-be5b-45e2-9510-96e04f3f746b">

It also allows us to drag a little to the left of the above arrow's position:

<img width="58" alt="screenshot_2541" src="https://github.com/phetsims/geometric-optics/assets/3046552/cb172765-1940-4ce2-9ddc-604041d107f1">

... and that's OK, because the position markers should not know anything about the width of the arrow head.

I'll discuss with @arouinfar via Zoom, to get sign off.

**Comment by pixelzoom** [comment] 2023-05-30 20:00
Cherry-picked in the above commits for geometric-optics 1.3 and geometric-optics-basics
 1.3.

**Comment by arouinfar** [comment] 2023-05-30 20:03
@pixelzoom everything in https://github.com/phetsims/geometric-optics/issues/473#issuecomment-1568921856 sounds good to me. Relaxing the drag bound fixes this issue and has no impact on usability, seems like a win-win.

**Comment by pixelzoom** [comment] 2023-05-30 20:04
Thanks @arouinfar.

@Nancy-Salpepi please verify in master. If it looks OK, change the label to "status:fixed-awaiting-deploy" and we'll verify in the next RC.

**Comment by Nancy-Salpepi** [comment] 2023-05-30 21:03
Looks good in master!

**Comment by pixelzoom** [comment] 2023-06-02 15:12
Ready for review in 1.3.0-rc.3. Please follow the steps in https://github.com/phetsims/geometric-optics/issues/473#issue-1727736911.

**Comment by KatieWoe** [comment] 2023-06-02 18:41
This looks good on Win 11 Chrome

**Closed by KatieWoe** 2023-06-02 18:41 UTC
Labels: type:bug, status:ready-for-review
