### ISSUE TITLE
Small arrows jump to a large minimum height

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#409] opened 2022-03-28 18:21 UTC
**Test device**
Chromebook and Dell
**Operating System**
Chrome OS and Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/787.
If you change the object an arrow (on either screen) and try to make the arrow small, it will jump to have a height of 20 cm or -20 cm. This happen with the blue and the red arrows and can feel quite odd

**Visuals**
![jumparrow](https://user-images.githubusercontent.com/41024075/160461621-e839d59e-7541-4ff3-ad75-de466caf8e45.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-rc.1/phet/geometric-optics_all_phet.html
Version: 1.1.0-rc.1 2022-03-18 20:41:59 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment] 2022-03-28 18:27
Thanks for reporting @KatieWoe.  

The arrow does (by design) have a minimum magnitude of 20 cm. Reasons: there's really no pegagogical value in making is smaller, we didn't want the head size to look scaled/distorted (which would be required with a very small magnitude), and we didn't want to the user to lose track of the arrow by making it so small that they'd have trouble grabbing it. 

Assigning to @arouinfar in case there's anything to reconsider here. Feel free to close.

**Comment by arouinfar** [comment] 2022-03-28 18:53
Thanks for the write-up @pixelzoom. I do not see any reason to allow smaller arrows, so I'll go ahead and close.

**Closed by arouinfar** 2022-03-28 18:53 UTC
