### ISSUE TITLE
Can't return items to toolbox when zoomed in

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics#388] opened 2022-03-18 21:24 UTC
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.2.1

**Browser**
Safari/Chrome

**Problem description**
Seen when testing the pan and zoom feature https://github.com/phetsims/qa/issues/785 for @jessegreenberg. 
If I am zoomed in a good bit, I can't get the rulers back in the toolbox. I also have difficulty returning the position markers. 
This happens in both GO and GO-Basics on all screens. 

I didn't have an issue returning the rulers in the published prototype version. 
I also tried another sim on the list https://github.com/phetsims/qa/issues/785 with a toolbox--CCK-DC. I was able to return the voltmeter and ammeter to the toolbox. 

**Steps to reproduce**
1. Go to any screen.
2. Zoom in (Press `command` + `+` 4 times)
3. Remove and try to return a ruler.
4. Remove and try to return a position marker--I can consistently get it back into the toolbox by releasing it on the right edge of the toolbox (see video 2).

**Visuals**

https://user-images.githubusercontent.com/87318828/159084472-da265e1b-bfff-40a3-a7e8-2f4cc18cdec6.mp4

https://user-images.githubusercontent.com/87318828/159084484-ec2f80f5-0a94-46f9-93bd-8d6c5db3d36e.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: Geometric Optics
URL: https://bayes.colorado.edu/dev/phettest/geometric-optics/geometric-optics_en.html?ea&brand=phet
Version: 1.2.0-dev.0 (unbuilt)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15
Language: en-US
Window: 1403x702
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jessegreenberg** [comment] 2022-03-18 21:56
This is happening because of https://github.com/phetsims/geometric-optics/blob/55d4490f804a649c846cf7ecc2670f08ff6d7e1e/js/common/view/tools/GOToolbox.ts#L48-L54

The listener isn't called if the `globalBounds` of the GOToolbox change. There isn't a `globalBoundsProperty` so here is another way that works by setting a function that returns the global bounds.

<details>

```patch
Index: js/common/view/tools/GOToolNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/tools/GOToolNode.ts b/js/common/view/tools/GOToolNode.ts
--- a/js/common/view/tools/GOToolNode.ts	(revision 7e397246142b004bfa676daeb59b04bc6f05a362)
+++ b/js/common/view/tools/GOToolNode.ts	(date 1647640037701)
@@ -31,8 +31,8 @@
 
   protected abstract dragListener: DragListener;
 
-  // Bounds of the toolbox, in global view coordinates. This tells the tool where to return to.
-  public toolboxBounds: Bounds2;
+  // Creates the Bounds2 of the toolbox, in the global view coordinates. This tells the tool where to return to.
+  public createToolboxBounds: () => Bounds2;
 
   // positions that are 'interesting' to measure, for the J+P hotkey
   protected jumpPoints: ToolJumpPoint[];
@@ -57,7 +57,7 @@
 
     super( options );
 
-    this.toolboxBounds = Bounds2.NOTHING; // to be set later via setToolboxBounds
+    this.createToolboxBounds = () => Bounds2.NOTHING; // to be set later via setToolboxBounds
     this.jumpPoints = [];
     this.jumpPointsIndex = 0;
 
@@ -67,11 +67,10 @@
   }
 
   /**
-   * Sets the bounds of the toolbox, so the ruler knows where to return to.
-   * @param toolboxBounds
+   * Sets a function that creates Bounds for the Toolbox, so the ruler knows where to return to.
    */
-  public setToolboxBounds( toolboxBounds: Bounds2 ): void {
-    this.toolboxBounds = toolboxBounds;
+  public setCreateToolboxBounds( createToolboxBounds: () => Bounds2 ): void {
+    this.createToolboxBounds = createToolboxBounds;
   }
 
   /**
@@ -108,7 +107,7 @@
    * @param map - optional function for mapping jump points to new positions
    */
   protected static getNextJumpPoint( jumpPoints: ToolJumpPoint[], toolPosition: Vector2,
-                                  map?: ( points: Vector2[] ) => Vector2[] ): Vector2 | null {
+                                     map?: ( points: Vector2[] ) => Vector2[] ): Vector2 | null {
 
     let nextPoint: Vector2 | undefined;
 
Index: js/common/view/tools/PositionMarkerNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/tools/PositionMarkerNode.ts b/js/common/view/tools/PositionMarkerNode.ts
--- a/js/common/view/tools/PositionMarkerNode.ts	(revision 7e397246142b004bfa676daeb59b04bc6f05a362)
+++ b/js/common/view/tools/PositionMarkerNode.ts	(date 1647639937656)
@@ -109,7 +109,7 @@
     } );
 
     // Return the tool to the toolbox if the marker's bounds intersect the toolbox.
-    const shouldReturnToToolbox = () => this.toolboxBounds.intersectsBounds( this.parentToGlobalBounds( this.bounds ) );
+    const shouldReturnToToolbox = () => this.createToolboxBounds().intersectsBounds( this.parentToGlobalBounds( this.bounds ) );
 
     // Dragging with the pointer.
     this.dragListener = new GOToolDragListener( positionMarker, this, zoomTransformProperty, this.dragBoundsProperty,
Index: js/common/view/tools/GORulerNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/tools/GORulerNode.ts b/js/common/view/tools/GORulerNode.ts
--- a/js/common/view/tools/GORulerNode.ts	(revision 7e397246142b004bfa676daeb59b04bc6f05a362)
+++ b/js/common/view/tools/GORulerNode.ts	(date 1647639788231)
@@ -138,7 +138,7 @@
 
     // Dragging with the pointer.
     // Return to the toolbox when the pointer is released inside the toolbox.
-    const dragReturnToToolbox = ( pointerPoint: Vector2 ) => this.toolboxBounds.containsPoint( pointerPoint );
+    const dragReturnToToolbox = ( pointerPoint: Vector2 ) => this.createToolboxBounds().containsPoint( pointerPoint );
     this.dragListener = new GOToolDragListener( ruler, this, zoomTransformProperty, this.dragBoundsProperty,
       dragReturnToToolbox, {
         tandem: providedOptions.tandem.createTandem( 'dragListener' )
@@ -147,7 +147,7 @@
 
     // Dragging with the keyboard.
     // Return the ruler to the toolbox if the ruler's center point is inside the toolbox.
-    const keyboardDragReturnToToolbox = () => this.toolboxBounds.containsPoint( this.parentToGlobalPoint( this.center ) );
+    const keyboardDragReturnToToolbox = () => this.createToolboxBounds().containsPoint( this.parentToGlobalPoint( this.center ) );
     const keyboardDragListener = new GOToolKeyboardDragListener( ruler, this, zoomTransformProperty,
       this.dragBoundsProperty, keyboardDragReturnToToolbox, {
         tandem: providedOptions.tandem.createTandem( 'keyboardDragListener' )
Index: js/common/view/tools/GOToolbox.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/tools/GOToolbox.ts b/js/common/view/tools/GOToolbox.ts
--- a/js/common/view/tools/GOToolbox.ts	(revision 7e397246142b004bfa676daeb59b04bc6f05a362)
+++ b/js/common/view/tools/GOToolbox.ts	(date 1647640148570)
@@ -49,8 +49,7 @@
     // This allows tools to determine when they have been dragged back to the toolbox.
     Property.multilink( [ this.boundsProperty, this.visibleProperty ],
       ( bounds: Bounds2, visible: boolean ) => {
-        const toolboxBounds = visible ? this.parentToGlobalBounds( bounds ) : Bounds2.NOTHING;
-        toolNodes.forEach( toolNode => toolNode.setToolboxBounds( toolboxBounds ) );
+        toolNodes.forEach( toolNode => toolNode.setCreateToolboxBounds( () => visible ? this.parentToGlobalBounds( bounds ) : Bounds2.NOTHING ) );
       } );
   }
 
```
</details>

**Comment by pixelzoom** [comment] 2022-03-18 22:01
Ah, looks like @jessegreenberg and I were commenting at the same time.  I'll discuss with him.

**Comment by pixelzoom** [comment] 2022-03-18 22:16
Discussed with @jessegreenberg on Zoom...  

The global coordinate frame doesn't change. But pan/zoom changes where everthing is in the global coordinate frame -- even things that don't change position/bounds in the scenegraph.  So you need to assume that nothing has static global bounds --  you cannot assume that something has the same global bounds as the last time that you checked.  

As @jessegreenberg mentioned, it might be nice to have a `globalBoundsProperty` on Node. But I can imagine that might be a performance problem, and might even make pan/zoom feel laggy.

I'll use the approach that @jessegreenberg suggested -- or something like it -- where the tools ask for the toolbox bounds on demand.    But I have a bad feeling that this type of problem is going to pop up in other sims that I've worked on, when we could assume that things that didn't move had static global bounds.

**Comment by pixelzoom** [comment] 2022-03-18 22:19
And lest I forget... Nice find @Nancy-Salpepi!

**Comment by pixelzoom** [comment] 2022-03-18 23:28
Fixed in master and 1.1 branches in the above commits.

@Nancy-Salpepi could you please verify in master? If it looks OK, change the label to "status:fixed-awaiting-deploy".

**Comment by Nancy-Salpepi** [comment] 2022-03-19 13:06
Looks good in master.

**Comment by pixelzoom** [comment] 2022-03-19 14:26
Unassigning, to be tested in the next RC.

**Comment by jessegreenberg** [comment] 2022-03-28 16:47
I realized later that this problem is not just specific to pan and zoom but would also happen for window resizes. The `globalBounds` of a Node will change in that case as well.

**Comment by pixelzoom** [comment] 2022-03-31 16:57
To verify in 1.1.0-rc.2, follow the "steps to reproduce" in https://github.com/phetsims/geometric-optics/issues/388#issue-1174046184.

**Comment by KatieWoe** [comment] 2022-04-01 16:36
Looks fixed. Will reopen if something comes up.

**Closed by KatieWoe** 2022-04-01 16:36 UTC
Labels: type:bug, status:ready-for-review
