### ISSUE TITLE
CT reentry detected

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#341] opened 2022-02-28 16:45 UTC
```
geometric-optics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/phet-io-wrappers/state/?sim=geometric-optics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22geometric-optics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1645997920856%22%2C%22timestamp%22%3A1646035369031%7D
Uncaught Error: Uncaught Error: Assertion failed: reentry detected, value=Vector2(-708, -21), oldValue=Vector2(-818.260452586207, -21)
Error: Assertion failed: reentry detected, value=Vector2(-708, -21), oldValue=Vector2(-818.260452586207, -21)
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/assert/js/assert.js:25:13)
at Vector2Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/chipper/dist/js/axon/js/Property.js:226:15)
at Vector2Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/chipper/dist/js/axon/js/Property.js:159:14)
at Vector2Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/chipper/dist/js/axon/js/Property.js:298:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/chipper/dist/js/geometric-optics/js/common/view/HTMLImageElementObjectNode.js:100:48
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/chipper/dist/js/axon/js/Property.js:228:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/chipper/dist/js/axon/js/Property.js:159:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/chipper/dist/js/axon/js/DerivedProperty.js:98:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1645997920856/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
id: Bayes Chrome
Snapshot from 2/27/2022, 2:38:40 PM
```

**Comment by pixelzoom** [comment] 2022-02-28 17:00
Duplicate of https://github.com/phetsims/geometric-optics/issues/325, closing.

**Closed by pixelzoom** 2022-02-28 17:00 UTC
Labels: type:automated-testing
