### ISSUE TITLE
Incorrect geometry is sometimes drawn for rays.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#209] opened 2021-09-23 23:57 UTC
_EDIT: This occurs for all objects and lights sources, for real and virtual rays._

While dragging the second light source around, I sometimes see odd geometry being drawn, presumably related to the rays. For example, see the pink triangle in the screenshot below.  I have not seen this with the first light source.

I saw this on MacBookPro16,1 + macOS 11.5 + Chrome 94.0.4606.54.  Not tested on other platforms.

@arouinfar Should this be addressed for the Prototype milestone?

<img width="989" alt="screenshot_1269" src="https://user-images.githubusercontent.com/3046552/134598587-b11d40a9-4a45-4b52-8cee-e8646b971488.png">

**Comment by pixelzoom** [comment] 2021-09-23 23:59
I also see this problem in [1.0.0-dev.9](https://phet-dev.colorado.edu/html/geometric-optics/1.0.0-dev.9/phet/geometric-optics_en_phet.html) from 7/30/21, before I started working on the sim.  So this has been an existing problem.  For example:

<img width="988" alt="screenshot_1270" src="https://user-images.githubusercontent.com/3046552/134598806-fbb014b9-d7c7-450f-8322-3ef6ae795be3.png">

**Comment by pixelzoom** [comment] 2021-09-24 20:51
Here's a particularly based example, in the screenshot below. And note that this is with an object, not a light source.   I've also seen this with the rays for the first object/light.

<img width="1047" alt="screenshot_1272" src="https://user-images.githubusercontent.com/3046552/134738195-90dbebc4-1c01-489a-b736-c65be6126000.png">

**Comment by pixelzoom** [comment] 2021-09-24 20:53
This problem does seem to be specific to rays for a virtual image. I have not seen this problem with a real image.

**Comment by pixelzoom** [comment] 2021-09-30 21:59
#216 makes this a moot issue - we're no longer showing virtual rays for light sources.

Closing.

**Comment by pixelzoom** [comment] 2021-10-05 17:16
Reopening. This is still occurring (frequently!) for real rays, for both light sources.  macOS 11.6 + Chrome 94.0.4606.71, untested on other platforms.

<img width="1133" alt="screenshot_1318" src="https://user-images.githubusercontent.com/3046552/136071441-4f02a94a-cd93-43cf-8dc9-385b64e4f6f8.png">

**Comment by pixelzoom** [comment] 2021-10-05 17:19
I'm not seeing this with Safari 15.0 or Firefox 93.0.

**Comment by pixelzoom** [comment] 2021-10-05 17:22
If I disable the drag bounds for Objects, I can also make this happen with Objects. It seems specific to the lower-left area of the screen, and the drag bounds for Objects (and their height) precludes them from being dragged there.

<img width="1134" alt="screenshot_1319" src="https://user-images.githubusercontent.com/3046552/136072170-33b574e1-abbf-45cb-8cf3-5ec3519e3b66.png">

**Comment by pixelzoom** [comment] 2021-10-05 17:23
@arouinfar Does this issue need to be addressed for the Prototype?  I have not started investigating, so I have no idea how much time will be involved in fixing this.

**Comment by pixelzoom** [comment] 2021-10-05 18:48
Ugh... It's also a problem for virtual rays associated with an Object. Again, in the same lower-right quadrant of the screen:

<img width="1133" alt="screenshot_1320" src="https://user-images.githubusercontent.com/3046552/136084452-09f33e2b-8a25-4b03-b5b7-02f638191d3f.png">

**Comment by pixelzoom** [comment] 2021-10-05 19:06
The code that creates the Shape for each individual ray is in LightRay.js.  In `updateShape`, this consists of calls to Shape `moveToPoint` and `lineTo`. 

The code that combines the individual rays is in LightRays.js.  Because we'll want to use different strokes for real vs virtual rays, there are separate Shapes for real and virtual rays. They are `this.realRaysShape` and `this.virtualRaysShape` respectively.  The Shapes of individual rays are combined in LightRays `addRayShape` by calling Shape `addSubpath`.  

I don't see any calls to Shape `close`, which is what I'd typically look for when I see closed (filled) paths like this.  And the Paths used to render the rays also have no `fill`, so it's curious that they are getting filled.

@jonathanolson any thoughts about what might be happening here?

**Comment by pixelzoom** [comment] 2021-10-05 21:23
Another example, this time NOT in the lower-left quadrant, and using a mirror:

<img width="1133" alt="screenshot_1323" src="https://user-images.githubusercontent.com/3046552/136104594-056be8ca-acf1-4914-b5c2-6b8d94949a66.png">

**Comment by samreid** [comment] 2021-10-05 23:32
I was able to reproduce the problem on macOS 11.6 on Chrome Version 94.0.4606.71 (Official Build) (arm64), and was surprised to see this problem with rootRenderer=canvas as well.  As a workaround, I tried separate Line instances for each Ray, and it seems to work around the problem (though would not be as fast performance unless we added pooling).  This could be a good practical case to understand the limits of our renderer, but I'm supplying the workaround in case we want to move forward with it in the meantime:

<details>

```diff

Index: js/common/model/LightRay.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/LightRay.js b/js/common/model/LightRay.js
--- a/js/common/model/LightRay.js	(revision 31bcd280e2eed3f36eb7aae045f862c353f0bfe1)
+++ b/js/common/model/LightRay.js	(date 1633474039852)
@@ -44,10 +44,10 @@
     assert && assert( typeof getProjectorScreenBisectorLine === 'function' );
 
     // @public (read-only) shape of the real rays - will be updated later
-    this.realShape = new Shape();
+    this.realShape = [];
 
     // @public (read-only) shape of the virtual rays - will be updated later
-    this.virtualShape = new Shape();
+    this.virtualShape = [];
 
     // {number} maximum travel distance if ray is unimpeded
     const distanceTraveled = GeometricOpticsQueryParameters.lightSpeed * time;
@@ -477,7 +477,8 @@
     const endPoint = ray.pointAtDistance( travelDistance );
 
     // add line to shape
-    shape.moveToPoint( ray.position ).lineToPoint( endPoint );
+    // shape.moveToPoint( ray.position ).lineToPoint( endPoint );
+    shape.push( { start: ray.position, end: endPoint } );
   }
 }
 
Index: js/common/model/LightRays.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/LightRays.js b/js/common/model/LightRays.js
--- a/js/common/model/LightRays.js	(revision 31bcd280e2eed3f36eb7aae045f862c353f0bfe1)
+++ b/js/common/model/LightRays.js	(date 1633474142646)
@@ -35,10 +35,10 @@
     this.targetPositionProperty = target.positionProperty;
 
     // @public (read-only) shape of a bundle of real rays at a point in time
-    this.realRay = new Shape();
+    this.realRay = [];
 
     // @public (read-only) shape of a bundle of virtual rays at a point in time
-    this.virtualRay = new Shape();
+    this.virtualRay = [];
 
     // @public tells view that it needs to update, fires after all rays are processed.
     this.raysProcessedEmitter = new Emitter();
@@ -57,10 +57,10 @@
       ( sourcePosition, lightRayMode, time, representation ) => {
 
         // @public (read-only)
-        this.realRay = new Shape();
+        this.realRay = [];
 
         // @public (read-only)
-        this.virtualRay = new Shape();
+        this.virtualRay = [];
 
         // {Vector2} the position the target
         const targetPoint = this.targetPositionProperty.value;
@@ -203,8 +203,8 @@
    * @param {Shape} typeRayShape
    */
   addRayShape( rayShape, typeRayShape ) {
-    rayShape.subpaths.forEach( subPath => {
-      typeRayShape.addSubpath( subPath );
+    rayShape.forEach( element => {
+      typeRayShape.push( element );
     } );
   }
 }
Index: js/common/view/LightRaysNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/LightRaysNode.js b/js/common/view/LightRaysNode.js
--- a/js/common/view/LightRaysNode.js	(revision 31bcd280e2eed3f36eb7aae045f862c353f0bfe1)
+++ b/js/common/view/LightRaysNode.js	(date 1633476321055)
@@ -13,6 +13,7 @@
 import ModelViewTransform2 from '../../../../phetcommon/js/view/ModelViewTransform2.js';
 import Node from '../../../../scenery/js/nodes/Node.js';
 import Path from '../../../../scenery/js/nodes/Path.js';
+import Line from '../../../../scenery/js/nodes/Line.js';
 import geometricOptics from '../../geometricOptics.js';
 import LightRays from '../model/LightRays.js';
 
@@ -39,14 +40,12 @@
       virtualRayLineWidth: 2
     }, options );
 
-    const realRayPath = new Path( modelViewTransform.modelToViewShape( lightRays.realRay ), {
+    const realRayPath = new Node( null, {
       stroke: options.realRayStroke,
       lineWidth: options.realRayLineWidth
     } );
 
-    const virtualRayPath = new Path( modelViewTransform.modelToViewShape( lightRays.virtualRay ), {
-      stroke: options.virtualRayStroke,
-      lineWidth: options.virtualRayLineWidth,
+    const virtualRayPath = new Node( null, {
 
       // Show virtual rays only for objects, not for light source. See https://github.com/phetsims/geometric-optics/issues/216
       visibleProperty: new DerivedProperty(
@@ -62,8 +61,25 @@
 
     // Update this Node when the model tells us that it's time to update.
     lightRays.raysProcessedEmitter.addListener( () => {
-      realRayPath.shape = modelViewTransform.modelToViewShape( lightRays.realRay );
-      virtualRayPath.shape = modelViewTransform.modelToViewShape( lightRays.virtualRay );
+      realRayPath.children = lightRays.realRay.map( term => {
+        return new Line(
+          modelViewTransform.modelToViewPosition( term.start ),
+          modelViewTransform.modelToViewPosition( term.end ), {
+            stroke: options.realRayStroke,
+            lineWidth: options.realRayLineWidth
+          }
+        );
+      } );
+
+      virtualRayPath.children = lightRays.virtualRay.map( term => {
+        return new Line(
+          modelViewTransform.modelToViewPosition( term.start ),
+          modelViewTransform.modelToViewPosition( term.end ), {
+            stroke: options.virtualRayStroke,
+            lineWidth: options.virtualRayLineWidth
+          }
+        );
+      } );
     } );
   }
 


```

</details>

**Comment by arouinfar** [comment] 2021-10-06 00:06
> Reopening. This is still occurring (frequently!) for real rays, for both light sources. macOS 11.6 + Chrome 94.0.4606.71.

I've seen this in macOS 10.15.7/Chrome 94.0.4606.61, but only as a brief flicker when using the sim in the color editor. I don't know how to reliably reproduce. I haven't seen it at all when using the regular unbuilt sim on master. 

> @arouinfar Does this issue need to be addressed for the Prototype? I'll assume it is, until I hear otherwise.

Since this seems to happen often on some platforms, I'd say it's blocking. The glitch looks pretty bad in the screenshots.

**Comment by pixelzoom** [comment] 2021-10-06 02:07
Thanks for the patch @samreid.  I had considered going this route (a Path for each ray). But I was trying to change the existing implementation as little as possible for the Prototype, especially code like this that involves animation.   I'll keep this in mind if I can't make forward progress on the existing implementation.

**Comment by pixelzoom** [comment] 2021-10-06 17:21
In https://github.com/phetsims/geometric-optics/issues/219, @samreid noted that Shape `addSubPath` is private.  So that tips the balance in favor of applying the patch identified in https://github.com/phetsims/geometric-optics/issues/209#issuecomment-935073761.

**Comment by arouinfar** [comment] 2021-10-07 19:09
@pixelzoom I haven't been able to reproduce in dev.17 and I'm not seeing a difference in performance compared to dev.15. Closing.

**Closed by arouinfar** 2021-10-07 19:09 UTC
Labels: type:bug, priority:2-high, status:blocks-sim-publication, status:ready-for-review
