### ISSUE TITLE
Pressing "Reset All" on Mirrors Screen allows free dragging of object

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/geometric-optics#333] opened 2022-02-26 02:28 UTC
Seen as part of #328 testing on master on Windows 10, Chrome

Pressing the "Reset All" button on the mirrors screen removes the constraint of objects only moving horizontally

See the video below for an example:

https://user-images.githubusercontent.com/4051174/155825508-1b139561-2c05-4b84-b5fa-36cc60c3a23d.mp4

**Comment by pixelzoom** [comment] 2022-02-26 02:54
Reproduced.  Steps:

1. Go to the Mirror screen
2. Note that the drag-lock button is disabled, and state is locked
3. Press reset all button
4. Note that drag-lock button is still disabled, but state is now UNLOCKED

**Comment by pixelzoom** [comment] 2022-02-26 03:13
Problem identified in the code.

In GOScreenView (the base class for both screens), dragLockedProperty is defined and its initial value is false:

```js
const dragLockedProperty = new BooleanProperty( false, {
```

In MirrorScreenView, dragLockedProperty is then changed based on whether we've select "Light":

```js
    if ( !options.isBasicsVersion ) {
      model.opticalObjectChoiceProperty.link( ( opticalObjectChoice: OpticalObjectChoice ) => {
        const isArrowObject = OpticalObjectChoice.isArrowObject( opticalObjectChoice );
        this.dragLockedProperty.value = !isArrowObject;
        this.dragLockedButton.enabled = isArrowObject;
      } );
    }
```

So reset all will reset to the initalized state, which was false. This could also present a problem with restoring iO state, since there could be an ordering dependency.   

Not sure how to resolved this, I'll need to think about it.

**Comment by pixelzoom** [comment] 2022-03-10 21:50
Fixed in master. @ariel-phet would you please verify, in GO and GO:Basics?

**Closed** 2022-03-11 16:31 UTC
Labels: type:bug, status:ready-for-review
