### ISSUE TITLE
Tool position changes if sim is launched while zoomed out

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics#467] opened 2023-05-12 12:27 UTC
**Test device**
MacBook Air M1 chip

**Operating System**
13.3.1

**Browser**
Safari/Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/938 and https://github.com/phetsims/qa/issues/939 in studio:
 the tools will change position if the sim was launched while zoomed in. 

**Steps to reproduce**
1. On either screen, press Zoom out button once
2. Place tools in the scene
3. Press Launch

**Visuals**
Studio:
<img width="1067" alt="Screenshot 2023-05-12 at 8 08 50 AM" src="https://github.com/phetsims/geometric-optics/assets/87318828/2fee3204-dae7-49d1-b4d2-5f10dde72099">

Standard Wrapper:
<img width="1433" alt="Screenshot 2023-05-12 at 8 09 07 AM" src="https://github.com/phetsims/geometric-optics/assets/87318828/1207a8de-9a93-4c37-9d4d-503268e7df74">

**Comment by pixelzoom** [comment] 2023-05-15 00:18
Reproduced in master.

**Comment by pixelzoom** [comment] 2023-05-15 00:44
This may be a problem with the order in which state is restored.  In PositionMarkerNode.ts, I see:

```ts
    // Origin is at centerTop.
    positionMarker.positionProperty.link( position => {
      this.centerTop = zoomTransformProperty.value.modelToViewPosition( position );
    } );

    // Update the marker's model position to match this Node's view position, so that the marker remains stationary
    // in the view, and the model position is correct.
    zoomTransformProperty.lazyLink( ( zoomTransform: ModelViewTransform2 ) => {
      positionMarker.positionProperty.value = zoomTransform.viewToModelPosition( this.centerTop );
    } );
```

And in GORulerNode.ts, I see something similar.  So depending on the order in which `positionProperty` and `zoomTransformProperty` are restored, this could end up with an incorrect result.

**Comment by pixelzoom** [comment] 2023-05-15 00:52
I tried this change in PositionMarkerNode.ts, but it resulted in no change.

```diff
    zoomTransformProperty.lazyLink( ( zoomTransform: ModelViewTransform2 ) => {
+      if ( !phet.joist.sim.isSettingPhetioStateProperty.value ) {
        positionMarker.positionProperty.value = zoomTransform.viewToModelPosition( this.centerTop );
+      }
    } );
```

**Comment by pixelzoom** [comment] 2023-05-15 00:55
Also tried this change in PositionMarkerNode.ts (`lazyLink` => `link`), which did not fix the problem:

```diff
-   zoomTransformProperty.lazyLink( ( zoomTransform: ModelViewTransform2 ) => {
+   zoomTransformProperty.link( ( zoomTransform: ModelViewTransform2 ) => {
      ruler.positionProperty.value = ( this.ruler.orientation === 'vertical' ) ?
                                     zoomTransform.viewToModelPosition( this.leftBottom ) :
                                     zoomTransform.viewToModelPosition( this.leftTop );
    } );
```

**Comment by pixelzoom** [comment] 2023-05-15 01:03
This also did not fix the problem for PositionMarkerNode.ts:

```diff
-    zoomTransformProperty.lazyLink( ( zoomTransform: ModelViewTransform2 ) => {
+    zoomTransformProperty.lazyLink( ( zoomTransform: ModelViewTransform2, oldZoomTransform: ModelViewTransform2 ) => {
+      if ( oldZoomTransform ) {
+        this.centerTop = oldZoomTransform.modelToViewPosition( positionMarker.positionProperty.value );
+      }
       positionMarker.positionProperty.value = zoomTransform.viewToModelPosition( this.centerTop );
     } );
```

**Comment by pixelzoom** [comment] 2023-05-15 01:11
This does fix the reported problem in PositionMarkerNode.ts. But it introduces a new problem - the position marker does not remain stationary when zooming in/out.  And it duplicates the listener for `positionMarker.positionProperty`.

```diff
    zoomTransformProperty.lazyLink( ( zoomTransform: ModelViewTransform2 ) => {
+     this.centerTop = zoomTransformProperty.value.modelToViewPosition( positionMarker.positionProperty.value );
      positionMarker.positionProperty.value = zoomTransform.viewToModelPosition( this.centerTop );
    } );
```

**Comment by pixelzoom** [comment] 2023-05-15 01:13
This fixes the problem and keeps the marker stationary when zooming in/out.   But it still duplicates the listener for `positionMarker.positionProperty`.  And it feels like an awful hack.
 
```diff
    zoomTransformProperty.lazyLink( ( zoomTransform: ModelViewTransform2 ) => {
      if ( phet.joist.sim.isSettingPhetioStateProperty.value ) {
        this.centerTop = zoomTransformProperty.value.modelToViewPosition( positionMarker.positionProperty.value );
      }
      positionMarker.positionProperty.value = zoomTransform.viewToModelPosition( this.centerTop );
    } );
```

**Comment by pixelzoom** [comment] 2023-05-16 14:02
Addressed in the above commit. @KatieWoe since @Nancy-Salpepi is out, could you please verify?  Verify using the steps reported in https://github.com/phetsims/geometric-optics/issues/467#issue-1707547723.  If it checks out OK, please close.

**Comment by pixelzoom** [comment] 2023-05-16 18:34
Thanks @KatieWoe.  It turns out that #469 is somewhat different, so it's OK to close this issue.

**Closed by pixelzoom** 2023-05-16 18:34 UTC
Labels: type:bug, dev:phet-io, status:ready-for-review

**Comment by pixelzoom** [comment] 2023-05-17 13:17
In the above commits, I improved the documentation to better describe why this fix is needed.
