### ISSUE TITLE
Incorrect ruler length with `shuffleListeners` query parameter

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#133] opened 2021-07-27 18:52 UTC
As part of the work on #129, we found that  run the simulation with  the query parameters ea&shuffleListeners lead to an unexpected behavior.  

Putting a ruler within the playArea and zooming out leas to a ruler that is twice as long as expected.

![image](https://user-images.githubusercontent.com/7633344/127211072-3d95466d-9c9e-485b-b548-ebb53d5414c7.png)

**Comment by pixelzoom** [comment] 2021-09-18 03:34
It would not be tragic if this sim did not support `?shuffleListeners`. So I'm going to unassign this for now, and we can decide whether we want to spend time on it when we get closer to public deployment.

**Comment by pixelzoom** [comment] 2021-12-07 19:59
The problem is in GeometricOpticsRulerNode:

```js
    zoomScaleProperty.link( zoomScale => {

      // update model length, so that view length remains the same
      ruler.scaleLength( zoomScale );

      // update view
      this.removeAllChildren();
      this.addChild( createRulerNode( this.ruler.length, zoomTransformProperty.value, zoomScale, options.rulerOptions ) );
    } );
```

This listener depends on zoomScaleProperty and zoomTransformProperty, but is only listenening to zoomScaleProperty.  It assumes that zoomTransformProperty is updated before zoomScaleProperty.

**Comment by pixelzoom** [comment] 2022-01-05 21:48
The rulers went through a major rewrite.  But this is still a problem, as indicated by this TODO in GORulerNode.js:

```ts
    //TODO https://github.com/phetsims/geometric-optics/issues/133 this listener also depends on zoomTransformProperty, so there's a problematic ordering dependency there
    zoomScaleProperty.link( zoomScale => {
```

**Comment by pixelzoom** [comment] 2022-03-02 00:49
Fixed in the above commit, tested with `shuffleListeners`, closing.

**Closed by pixelzoom** 2022-03-02 00:49 UTC
