### ISSUE TITLE
Assertion failed in Spotlight.getIntersection()

### ISSUE THREAD

**Issue by zepumph** [phetsims/geometric-optics#156] opened 2021-08-04 12:53 UTC
I hit this assertion during my first time playing with the sim for https://github.com/phetsims/geometric-optics/issues/154. I don't feel like I did anything out of the ordinary, or even tried to break it. I pretty much just moved the lens a small amount, and then dragged around the pencil, eventually leading to the bottom left, as shown in the picture. Sorry I didn't have my dev tools open so that I could have paused in the stack trace to give more information. Note the "reentry detected" assertion is likely just downstream of the original problem, and you can probably ignore it. 

![image](https://user-images.githubusercontent.com/6856943/128183542-5967bf2d-699c-4ba8-b8cc-33e0e7a55198.png)

```
Assertion failed
assert.js:25 Uncaught Error: Assertion failed
    at window.assertions.assertFunction (assert.js:25)
    at Function.intersect (BoundsIntersection.js:213)
    at Function.intersect (Segment.js:739)
    at Graph.eliminateIntersection (Graph.js:694)
    at Graph.computeSimplifiedFaces (Graph.js:189)
    at Function.binaryResult (Graph.js:1286)
    at Spotlight.getIntersection (Spotlight.js:193)
    at Spotlight.js:55
    at getDerivedValue (DerivedProperty.js:30)
    at DerivedProperty.getDerivedPropertyListener (DerivedProperty.js:112)
assert.js:21 Assertion failed: reentry detected, value=Vector2(112.78102820930101, 12.882638828305552), oldValue=Vector2(112.78102820930101, 12.882638828305552)
assert.js:25 Uncaught Error: Assertion failed: reentry detected, value=Vector2(112.78102820930101, 12.882638828305552), oldValue=Vector2(112.78102820930101, 12.882638828305552)
    at window.assertions.assertFunction (assert.js:25)
    at DerivedProperty._notifyListeners (Property.js:268)
    at DerivedProperty.set (Property.js:186)
    at DerivedProperty.getDerivedPropertyListener (DerivedProperty.js:112)
    at TinyProperty.emit (TinyEmitter.js:86)
    at Vector2Property._notifyListeners (Property.js:271)
    at Vector2Property.set (Property.js:186)
    at Vector2Property.set value [as value] (Property.js:341)
    at Optic.setVerticalCoordinate (Optic.js:331)
    at OpticNode.js:119
```

**Comment by veillette** [comment] 2021-08-04 14:23
Thanks @zepumph. 
This is related to the spotlight and projectorScreen. The spotlight model gets update, independent of the visibility of the projectorScreenNode.  We have made progress on a method to reproduce it ( see #72) but we have not manage to track it down.

**Comment by pixelzoom** [comment] 2021-09-29 17:17
@arouinfar should this be addressed for the prototype? I have not investigated whether it causes the sim to crash in practice.

**Comment by pixelzoom** [comment] 2021-09-29 17:44
This seems related to (duplicate of?) https://github.com/phetsims/geometric-optics/issues/163.  But I'm hesitant to close it, because there seems to be more than 1 problem that the sim is hitting in kite when Spotlight.getIntersection() is called.

**Comment by arouinfar** [comment] 2021-10-01 17:24
In https://github.com/phetsims/geometric-optics/issues/215#issuecomment-931621318 we decided not to address assertion failure issues for the prototype, so back to @pixelzoom.

**Comment by pixelzoom** [comment] 2021-10-01 22:56
Since this is not in the prototype, unassigning until I start working on public production issues.

**Comment by pixelzoom** [comment] 2022-01-04 23:30
This is probably the same as https://github.com/phetsims/geometric-optics/issues/163, since they both mention `Spotlight.getIntersection`, and both fail in `Graph.eliminateIntersection`.   But the 2 GitHub issues contain different information and reports, so I'll leave them both open.  Since https://github.com/phetsims/geometric-optics/issues/163 is assigned to @jonathanolson, assigning this issue to him as well.

**Comment by jonathanolson** [comment] 2022-01-05 01:30
Has this been reproduced since https://github.com/phetsims/kite/issues/90 was fixed?

**Comment by pixelzoom** [comment] 2022-01-05 02:01
I've never been able to reproduce this.  So I'll go ahead and close this, assuming that it's a duplicate of https://github.com/phetsims/geometric-optics/issues/163, and QA is testing that issue.

**Closed by pixelzoom** 2022-01-05 02:01 UTC
Labels: type:bug, dev:code-review
