### ISSUE TITLE
Spotlight.getIntersection() results in assertion failure in kite.

### ISSUE THREAD

**Issue by zepumph** [phetsims/geometric-optics#163] opened 2021-08-04 15:40 UTC
While playing with the sim with the second source turned on, I found that the sim just froze, with no errors. I was able to pause in the chrome dev tools fast enough that the page didn't crash. It looks like there is a loop in `BoundsIntersections.pushSubdivisions()`. Note the current length of the "intersections" array below (13962399).

![image](https://user-images.githubusercontent.com/6856943/128209430-09fc20c7-7146-4198-8cc1-8db58f615756.png)

I will try to data dump as much as possible here from the stack for reproduceability. I think the important bits are coming from Spotlight.getIntersection(), so I'll go from there.

```

screenPosition
>Vector2 {x: 200, y: 0}

opticPosition
>Vector2 {x: 0, y: 0}

opticDiameter
>80

targetPosition
>Vector2 {x: 187.97374935890778, y: -66.22766706581093}

screenShape.toString()
>"new kite.Shape( 'M 172.00000000000000000000 39.00000000000000000000 L 172.00000000000000000000 -51.00000000000000000000 L 225.00000000000000000000 -83.00000000000000000000 L 225.00000000000000000000 72.00000000000000000000 L 172.00000000000000000000 39.00000000000000000000 Z ' )"

diskShape.toString()
>"new kite.Shape( 'M 201.27956700139799295357 -70.46480403958862837044 A 2.55913400279601432885 1.27956700139800716443 450 0 1 198.72043299860195020301 -70.46480403958862837044 A 2.55913400279601432885 1.27956700139800716443 450 0 1 201.27956700139799295357 -70.46480403958862837044 Z ' )"
```

I hope this is helpful, and good luck.

**Comment by zepumph** [comment] 2021-08-04 16:59
https://github.com/phetsims/geometric-optics/issues/154

**Comment by veillette** [comment] 2021-08-04 20:30
I rendered the shapes.
Visually, we get (I cropped the image):
![image](https://user-images.githubusercontent.com/7633344/128250495-0f467e5a-ba24-4e28-92c0-04f6f540eccf.png)

**Comment by pixelzoom** [comment] 2021-09-14 20:24
I was asked to evaluate this for https://github.com/phetsims/geometric-optics/milestone/1, so self-assigning.

**Comment by pixelzoom** [comment] 2021-09-14 21:02
>

**Comment by pixelzoom** [comment] 2021-09-14 21:03
@zepumph said:
> While playing with the sim with the second source turned on, I found that the sim just froze, with no errors. ...


It would be really helpful to have steps to reproduce. I've been playing with the sim for 15 minutes and can't reproduce this problem.  @zepumph do you recall how you reproduced this?

**Comment by zepumph** [comment] 2021-09-14 21:21
>@zepumph do you recall how you reproduced this?

I do not! And I remember feeling like it would be really hard to reproduce during it, which is why I tried to gather so much info from the environment. I think that @veillette had a good idea about how to draw the two shapes I posted in such a way that they created the single point of overlap. I'm sorry I can't be of more help here.

**Comment by pixelzoom** [comment] 2021-09-14 22:52
While I can't reproduce this, the stack trace points to this being a problem in kite (the common-code repo for shapes).   Here's the part of the Stack trace (from the 1st comment above) that's relevant:

<img width="334" alt="screenshot_1240" src="https://user-images.githubusercontent.com/3046552/133343998-d810afc8-92f0-45a4-aec1-bbe4cf19feb4.png">
  
Spotlight.js is sim-specific code, and here's where it passes things off to kite:

```js
      // find the intersection of the two shapes
      return Graph.binaryResult( screenShape, diskShape, Graph.BINARY_NONZERO_INTERSECTION );
```

I took a quick dive into the kite methods, but this is code that I'm not familiar with. You'll need to have @jonathanolson take it from here.  Assigning to @kathy-phet and @arouinfar to prioritize.

**Comment by pixelzoom** [comment] 2021-09-23 21:24
9/23/21 design meeting:

@KatieWoe please test on master. If you can reproduced, please adds steps here.

**Comment by Nancy-Salpepi** [comment] 2021-09-24 13:48
I was able to get the sim to freeze twice just by moving the pencil around with the second source placed in the center of the pencil. It is not necessary to change any other settings in the sim. The sim froze when the pencil was in different places, so I have not been able to nail down a set of steps to reproduce. However, it wasn't a runtime error that I saw. It was an assertion error.
<img width="684" alt="Screen Shot 2021-09-24 at 9 10 58 AM" src="https://user-images.githubusercontent.com/87318828/134684881-9c225b49-0d83-46aa-bb26-9052c2ebfb12.png">

![GOcut](https://user-images.githubusercontent.com/87318828/134684929-d94a3f21-300f-496c-9163-d93b297f0bce.gif)

**Comment by pixelzoom** [comment] 2021-09-24 14:42
@Nancy-Salpepi can you please provide the usual Troubleshooting info?  And how were you running the sim? If assertions were enabled, I'm guessing that you were usin phettest or a local copy.

**Comment by pixelzoom** [comment] 2021-09-24 14:45
Since this is a caught assertion, it's being run in an unbuilt version, because assertions are stripped out in built version.  We may want to see what the repercussions are in a built version.  What does the user see (if anything) when this occurs, and does the sim continue to run OK?  So...

 @Nancy-Salpepi could you please test build version [1.0.0-dev.48](https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.0-dev.48/phet/fourier-making-waves_en_phet.html)? What happens where you follow the same testing procedure that you described in https://github.com/phetsims/geometric-optics/issues/163#issuecomment-926639431?

**Comment by Nancy-Salpepi** [comment] 2021-09-24 14:49
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.5.2

**Browser**
chrome

**Problem description**
On Master:
I was able to get the sim to freeze four times just by moving the pencil around with the second source placed in the center of the pencil. It is not necessary to change any other settings in the sim. The sim froze when the pencil was in different places, so I have not been able to nail down a set of steps to reproduce. However, it wasn't a runtime error that I saw. It was an assertion error.
<img width="684" alt="Screen Shot 2021-09-24 at 9 10 58 AM" src="https://user-images.githubusercontent.com/87318828/134684881-9c225b49-0d83-46aa-bb26-9052c2ebfb12.png">

**Steps to reproduce**
It has frozen in 4 different places so far. Still working on reproducible steps. 

**Visuals**
see above https://github.com/phetsims/geometric-optics/issues/163#issuecomment-926639431

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: Geometric Optics
URL: https://bayes.colorado.edu/dev/phettest/geometric-optics/geometric-optics_en.html?ea&brand=phet
Version: 1.0.0-dev.12 (unbuilt)
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
Language: en-US
Window: 1440x690
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by Nancy-Salpepi** [comment] 2021-09-24 14:53
@pixelzoom link provided in your above comment https://github.com/phetsims/geometric-optics/issues/163#issuecomment-926685101 took me to Fourier.

**Comment by pixelzoom** [comment] 2021-09-24 15:31
Sorry, link fixed in comment above.  It's https://phet-dev.colorado.edu/html/geometric-optics/1.0.0-dev.12/phet/geometric-optics_en_phet.html

**Comment by Nancy-Salpepi** [comment] 2021-09-24 17:59
With MacBook + chrome:
Using 1.0.0-dev.12 and the same testing procedure described in https://github.com/phetsims/geometric-optics/issues/163#issuecomment-926639431, I was unable to reproduce the sim freezing. 

I will continue to use this built version and make additional manipulations to try and reproduce the original error described in https://github.com/phetsims/geometric-optics/issues/163#issue-960647878.

**Comment by kathy-phet** [comment] 2021-09-24 18:48
@Nancy-Salpepi - A while back I was able to freeze the sim by changing the refraction index in different circumstances. I know code has changed since then, but you might try wiggling other knobs too to see if you can induce any crashes at all in the built version. Thanks for banging on this issue!

**Comment by KatieWoe** [comment] 2021-09-24 19:04
I wanted to take a look at this myself and went to master to get a look at the bug. I wasn't able to reproduce it there, and @Nancy-Salpepi said she hasn't been able to either. Has something changed?

**Comment by pixelzoom** [comment] 2021-09-24 19:48
@KatieWoe I beleive that @Nancy-Salpepi said that she DID reproduce the problem in master (unbuilt, assertion enabled), but DID NOT reproduce the problem in a dev version (built, assertions stripped).  @Nancy-Salpepi do I understand that correctly?

And no, nothing has been changed.

**Comment by KatieWoe** [comment] 2021-09-24 19:57
She said this to me about half an hour ago. That she could reproduce it this morning, but was unable to now. @Nancy-Salpepi can you confirm my understanding?

**Comment by KatieWoe** [comment] 2021-09-24 20:00
Actually, I finally did manage to reproduce this in master on the mirror screen. It took me quite a while though.

**Comment by Nancy-Salpepi** [comment] 2021-09-24 20:32
I am having a harder time reproducing in Master now. Not sure why. It happened so easily for me this morning....with the assertion error each time.

**Comment by pixelzoom** [comment] 2021-09-24 20:39
@Nancy-Salpepi said:
> While playing with the sim with the second source turned on, I found that the sim just froze, with no errors.  ...

Can you be more specific about "playing with the sim"?   Do you recall what you were doing when the sim froze? Were you dragging something? Changing radio buttons or checkboxes?  Something else?

**Comment by pixelzoom** [comment] 2021-09-24 20:44
@Nancy-Salpepi said:
> While playing with the sim with the second source turned on, I found that the sim just froze, with no errors.  ...

Can you be more specific about "playing with the sim"?   Was it always the situation shown in the animation in https://github.com/phetsims/geometric-optics/issues/163#issuecomment-926639431? Or could you get the sim to fail doing other things? Were you always dragging something? What settings did you have turned on? ...  

I have yet to encounter this failure.

**Comment by KatieWoe** [comment] 2021-09-24 20:57
I was able to get this on the debug version of the sim. Still haven't gotten it in the non-debug version.
Steps were turning on the second source, moving it to the middle to the object. Moving the slider controlling the mirror's properties, and dragging the object around randomly until the crash happened.
<img width="960" alt="inbuilddebug" src="https://user-images.githubusercontent.com/41024075/134738890-9e77522c-2d7c-4f6a-927d-7bd2e309d5ef.png">

**Comment by Nancy-Salpepi** [comment] 2021-09-24 21:10
Nice @KatieWoe!
I know for certain that I never moved a slider before it happened. 

The first time it occurred, I had been changing lots of things (checking and unchecking boxes/radiobuttons/zoom) and it occurred while I was dragging the pencil with only the second source checked after about 6 minutes. I filmed the entire thing but it is a huge file. 
I was then able to get it to happen in my next two attempts by trying to reproduce the portion of the video I posted. I only added the second source and moved it to the middle of the pencil and tried to do what was in the video. I didn't change anything else and was able to get it to freeze. 
The last time, I only added the second source and moved the pencil around, but it occurred after pressing the reset button. It froze almost immediately after the reset. 
<img width="1440" alt="Screen Shot 2021-09-24 at 10 38 14 AM" src="https://user-images.githubusercontent.com/87318828/134737745-d39e5c2d-bc09-47c3-b9ac-b3d12b0d4638.png">

**Comment by pixelzoom** [comment] 2021-09-24 21:36
Thanks for the additional info @Nancy-Salpepi and @KatieWoe.  Unfortunately, I've still be unsuccessful at reproducing this.  But based on your tests, I'll offer the following conclusions:

* It happens regularly. It is not a corner case. 
* In unbuilt versions of the sim, it hits an assertion and the sim stops.
* In built versions of the sim (what a user would be using), it seems to keep running OK.

So it would probably be OK to publish a prototype with this problem.  But if you really want to be safe, we should probably address it, or at least get @jonathanolson's opinion.  @kathy-phet @arouinfar your call.

**Comment by Nancy-Salpepi** [comment] 2021-09-27 16:11
Just a quick update from my end...I tested 1.0.0-dev12 for a couple more hours this morning using MacBook Air + chrome. With the second source on, I manipulated the sliders, buttons and switched screens and scenes. There were no console errors nor did I experience a crash.

**Comment by kathy-phet** [comment] 2021-09-27 16:20
That's exciting, @Nancy-Salpepi !

**Comment by jonathanolson** [comment] 2021-09-28 18:35
I briefly looked at the case @zepumph noted, and created https://github.com/phetsims/kite/issues/90. It's not handling well intersections between two segments that are essentially a single elliptical arc split incredibly close to a horizontal tangent. We could both (a) improve arbitrary intersection, but to handle this case better (b) handling ellipse/circle intersections where they only differ by start/end angles.

**Comment by pixelzoom** [comment] 2021-09-29 17:17
I'm still not clear on whether this needs to be addressed for the prototype. Labeling for design meeting.

**Comment by jonathanolson** [comment] 2021-09-29 20:12
Additionally, let me know if I should bump up kite failures in priority here.

**Comment by pixelzoom** [comment] 2021-09-30 22:13
9/30/21 design meeting:

Since this doesn't cause a hard failure in practice (assertions are stripped in built versions), we will not address this for the Prototype milestone.  It should be addressed for the first public publication.

**Comment by jonathanolson** [comment] 2021-10-04 19:19
I've handled what was causing the particular failure identified by @zepumph in this issue. I'm going to leave self-assigned until I see if there might be other triggers (and review the other related issues).

**Comment by pixelzoom** [comment] 2022-01-04 23:33
> I've handled what was causing the particular failure identified by @zepumph in this issue. 

Where did you handle it? Is there a sha that you can reference?

> I'm going to leave self-assigned until I see if there might be other triggers (and review the other related issues).

What's the timeframe for completing this?

**Comment by jonathanolson** [comment] 2022-01-05 01:29
> Where did you handle it? Is there a sha that you can reference? There are no commits linked to this issue.

Commits were tagged to the common issue linked to this: https://github.com/phetsims/kite/issues/90

> What's the timeframe for completing this?

Presumably if it's not failing, we could close this?

**Comment by pixelzoom** [comment] 2022-01-05 02:00
I was never able to successfully reproduce this, but QA did.  @KatieWoe could you (or someone you assign) please verify that this has been fixed?

**Comment by KatieWoe** [comment] 2022-01-05 20:18
A few of us have tested this since this morning and so far we have not reproduced the issue. It looks fixed so far, but since it was difficult to reproduce in the first place, it is hard to be sure.

**Comment by pixelzoom** [comment] 2022-01-05 21:07
Thanks QA team.  Let's consider this resolved.  Closing.

**Closed by pixelzoom** 2022-01-05 21:07 UTC
Labels: type:bug, dev:code-review, status:ready-for-qa
