### ISSUE TITLE
Turn on PhET-iO validation by default?

### ISSUE THREAD

**Issue by zepumph** [phetsims/geometric-optics#307] opened 2022-02-12 03:38 UTC
I think this sim is well past the point where I would recommend turning on validation. It will mostly help keep track of small errors while developing. It looks like you have every required tandem taken care of at this point, so I don't see any value in keeping validation off. 

Discovered while working on https://github.com/phetsims/scenery/issues/1360

**Comment by pixelzoom** [comment] 2022-02-12 03:39
Duplicate of https://github.com/phetsims/geometric-optics/issues/248.

**Closed by pixelzoom** 2022-02-12 03:39 UTC
