### ISSUE TITLE
Ruler startDrag is affected by zoom

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#56] opened 2021-06-24 17:02 UTC
When I start the simulation, change the zoom level, and then drag a ruler out of the toolbox, the initial position of the ruler when I start the drag is not where my pointer is.  The ruler is created on the left side of the sim screen and continues to be created at that location for the duration of the sim.

This issue does not happen when I click on the rulers before ever changing the zoom level.  When the rulers are accessed before the zoom level is changed, the rulers are created exactly below the pointer.

**Comment by veillette** [comment] 2021-07-06 16:04
This is related to the dispose function.

````
    // update rulers when scale changes
    absoluteScaleProperty.link( absoluteScale => {

      // since RulerNode is not mutable, remove all children
      this.removeAllChildren();

      // dispose of the rulers
      this.disposeRulers();

      // create and add rulers, keeping a reference to the added ruler
      this.horizontalRulerNode = addRulerNode( rulers.horizontal, absoluteScale, this.visibleHorizontalProperty );
      this.verticalRulerNode = addRulerNode( rulers.vertical, absoluteScale, this.visibleVerticalProperty );

    } );
````

once the RulersNode have been created, we need to remove the children and dispose of the rulerNode.

**Comment by veillette** [comment] 2021-07-27 20:08
I can confirm that if we remove the dispose call, then the issue disappears ( but then we created a memory leak). 
If we add back the dispose function but remove the call to super.dispose, then the problem goes away. 

The initial positioning of the rulerNode is done in toolboxPanel where we create a forward listener on the icon node.
````
  iconNode.addInputListener( DragListener.createForwardingListener( event => {
        if ( !visibleRulerProperty.value ) {
          visibleRulerProperty.value = true;
          rulerNode.center = this.globalToParentPoint( event.pointer.point );
          rulerNode.startDrag( event );
        }
````

If we do not click on the zoom button initially, then the dispose function is never call, and we can find the rulerNode is an instance of GeometricOpticsRulerNode , that is attached to a parent. 

However, after click on the zoom button, the dispose function on the GeometricOpticRulerNode has been called and we find the the rulerNode is a GeometricOpticsRulerNode but does not have any parent at that point. 

 

After

**Comment by veillette** [comment] 2021-07-27 20:32
The dispose function in GeometricOpticsRulerNode is the only one in the simulation. We have tried to create a simulation where the listeners, observers are created for the lifetime of the simulation to avoid creating memory leak.  However, because RulerNode from scenery is not mutable and that we have extended GeometricOpticsRulerNode with RulerNode, we have been forced to create a brand new GeometricOpticsRulerNode for each zoom level. 

In may be a superior approach to have GeometricOpticsRulerNode extend Node instead of RulerNode. 
The Scenery RulerNode would be created by composition instead.
Hence, it would be possible to attach all the listeners  directly onto GeometricOpticRulerNode as before, but we would not need to dispose of them since GeometricOpticsRulerNode would exist for the lifetime of the simulation.

**Comment by veillette** [comment] 2021-07-29 17:07
```
    // updates rulers when scale changes
    absoluteScaleProperty.link( absoluteScale => {

      // since RulerNode is not mutable, remove all children
      this.removeAllChildren();

      // dispose of the ruler listeners
      this.disposeRulers();

      // creates and add rulers, keeping a reference to the added ruler
      this.horizontalRulerNode = addRulerNode( rulers.horizontal, absoluteScale, this.visibleHorizontalProperty );
      this.verticalRulerNode = addRulerNode( rulers.vertical, absoluteScale, this.visibleVerticalProperty );

    } );
```

I think the problem resides with the reassigning of a new object this.horizontalRulerNode and this.verticalRulerNode.

The new rulers are added to the scene graph but this.horizontalRulerNode does not point to the new ruler but the old one.
The startDrag method on the old ruler still exists but we can center it since the old ruler is not longer attach to the scene graph.

This would explain how we seem to be forwarding event, when in reality, the new ruler simply appear at a position set by the model.

**Comment by veillette** [comment] 2021-08-04 19:46
As explained above, I have addressed this issue  by having GeometricOpticsRulerNode extend Node instead of RulerNode.
The Scenery RulerNode would be created by composition instead.

This has several benefits:
- We do not need to instantiate new GeometricOpticsRulerNodes after the initialization. 
- All the listeners that were  attached to the GeometricOpticsRuleNodes do not need to be disposed anymore since they exist for the lifetime of the simulation.
- It adresses the bug in this issue.
- It allows to transfer the visibility of the ruler directly onto GeometricOpticsRulerNode instead of the Layers.

This is large refactoring but it will be easier to maintain in the long run.

**Comment by pixelzoom** [comment] 2021-09-16 00:46
This issue appears to have been addressed, and is no longer reproducible using the steps described.  Closing.

**Closed by pixelzoom** 2021-09-16 00:46 UTC
Labels: type:bug
