### ISSUE TITLE
Left behind pointer areas are still interactive

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#396] opened 2022-03-21 21:38 UTC
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/787
If you drag a ruler out of the tool box, then click that area of the tool box again, the ruler jumps back to the box as if it had just been grabbed.
**Steps to reproduce**
1. Drag a ruler out of a tool box
2. Click the empty space in the tool box
3. Using the `?showPointerAreas` parameter may help

**Visuals**
![reclickruler](https://user-images.githubusercontent.com/41024075/159368044-23fa2068-b506-4706-8edd-0488ab44882f.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-rc.1/phet/geometric-optics_all_phet.html?showPointerAreas
Version: 1.1.0-rc.1 2022-03-18 20:41:59 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0
Language: en-US
Window: 1280x667
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment] 2022-03-21 23:00
There's a wrapper Node around each icon, which was added so that visibility of the icons in the toolbox can be controlled independently of moving the tools in/out of the toolbox.  The problem was that those wrapper Nodes also had the input listeners attached to them.  Fixed in master and 1.1 branches.  

@KatieWoe please verify in master. Change label to "status:fixed-awaiting-deploy" if it looks OK.

**Comment by KatieWoe** [comment] 2022-03-22 14:40
Looks good in master

**Comment by pixelzoom** [comment] 2022-03-31 19:40
To verify in 1.1.0-rc.2, follow the steps to reproduce in https://github.com/phetsims/geometric-optics/issues/396#issue-1175971294.

Please close after verifying.

**Comment by Nancy-Salpepi** [comment] 2022-04-01 17:19
Looks fixed! Will reopen if something comes up.

**Closed by Nancy-Salpepi** 2022-04-01 17:19 UTC
Labels: type:bug, status:ready-for-review
